Support ARM64 arch in Mailhog role
roots/trellis pull request #1432
Opened 2022-10-13 00:42 UTC by swalkinshaw

`geerlingguy.mailhog` doesn't support arm64 (Apple Silicon) because the underlying binaries (`mailhog` and `mhsendmail`) don't have official `arm64` builds.

To support this by default, we need to override the url variables to point to forks that have these builds.

This adds a new "shim loader" `mailhog` role which simply loads the proper vars and then passes them to the included `geerlingguy.mailhog` role.

2022-10-13 06:20 UTC, TangRufus commented
Does https://github.com/geerlingguy/ansible-role-mailhog/pull/29/ solves the issue?

2022-10-13 13:17 UTC, swalkinshaw commented
Unfortunately not because that still points to the official repos which don't contain builds for arm64; only 32bit ARM.

2022-10-14 21:16 UTC, retlehs requested changes
Currently breaks provisioning at this step:

```
TASK [php : Copy PHP-FPM configuration file] ***********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: {{ mailhog_install_dir }}/mhsendmail: 'mailhog_install_dir' is undefined
fatal: [default]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ mailhog_install_dir }}/mhsendmail: 'mailhog_install_dir' is undefined"}
```

2022-10-15 17:24 UTC, retlehs approved these changes

2022-10-15 18:06 UTC, merged